@echo off
@cls
:- Generated by OTTO
:- 
:-   build       SFL build script
:- 
:-   Notes:      See SFL HTML documentation kit for details.
:-               On-line reference is at http://www.imatix.com.
:-               It's probably not a good idea to modify this script.
:- 
:-   Syntax:     chmod +x build; build        (UNIX)
:-               @build                       (VMS)
:- 
:-   Copyright:  Copyright (c) 1996 iMatix
:-   License:    This is free software; you can redistribute it and/or modify
:-               it under the terms of the SFL License Agreement as provided
:-               in the file LICENSE.TXT.  This software is distributed in
:-               the hope that it will be useful, but without any warranty.
:- 
rem  -------------------------------------------------------------------------
rem		File name: TCBUILD.BAT which is modified from BUILD.BAT
rem		Purpose:   For using Turbo C 2.01 on DOS to compiling SFL v1.4 source
rem                code.
rem		Change notice:
rem
rem 		1) define CCNAME, CCDIR, INCDEF, LIBDIR, CC,CFLAGS, LIB
rem 		2) change all 'call c' to '%CC% %CFLAGS%'
rem 		3) change all 'lib-+'XXX to '%LIB% +'XXX
rem 		4) delete ';' at end of each line using '%LIB%'
rem
rem 	Modified by Jau-Bing Lin on 2023/10/03
rem  -------------------------------------------------------------------------
 
set CCNAME=tc
set CCDIR=\tc
set INCDEF=%CCDIR%\include
set LIBDIR=%CCDIR%\lib
set CC=%CCDIR%\bin\tcc
set CFLAGS=-c -f -O -Z -w -C -I%INCDEF% -L%LIBDIR%
set LIB=%CCDIR%\bin\tlib

cls
echo.
echo ----- Initial compiler and its include file and library path -----
echo.
echo CCNAME=%CCNAME
echo CCDIR=%CCDIR
echo INCDEF=%INCDEF
echo LIBDIR=%LIBDIR
echo CC=%CC% %CFLAGS%
echo LIB=%LIB%
echo.
echo ----- End of initialization -----
echo.
echo.
echo Building Standard Function Library version 1.4
echo Press any key to continue, or Ctrl-C to abort.

:- pause
pause
echo.

echo Checking for required files...
@echo on
:- require prelude.h
if exist prelude.h goto end_1
    echo prelude.h missing - aborting
    goto exit
:end_1
 
:- require sflbits.h  sflbits.c
if exist sflbits.h goto end_2
    echo sflbits.h missing - aborting
    goto exit
:end_2
if exist sflbits.c goto end_3
    echo sflbits.c missing - aborting
    goto exit
:end_3
 
:- require sflcgi.h   sflcgi.c
if exist sflcgi.h goto end_4
    echo sflcgi.h missing - aborting
    goto exit
:end_4
if exist sflcgi.c goto end_5
    echo sflcgi.c missing - aborting
    goto exit
:end_5
 
:- require sflcomp.h  sflcomp.c
if exist sflcomp.h goto end_6
    echo sflcomp.h missing - aborting
    goto exit
:end_6
if exist sflcomp.c goto end_7
    echo sflcomp.c missing - aborting
    goto exit
:end_7
 
:- require sflconv.h  sflcvbs.c  sflcvdp.c  sflcvds.c  sflcvns.c
if exist sflconv.h goto end_8
    echo sflconv.h missing - aborting
    goto exit
:end_8
if exist sflcvbs.c goto end_9
    echo sflcvbs.c missing - aborting
    goto exit
:end_9
if exist sflcvdp.c goto end_10
    echo sflcvdp.c missing - aborting
    goto exit
:end_10
if exist sflcvds.c goto end_11
    echo sflcvds.c missing - aborting
    goto exit
:end_11
if exist sflcvns.c goto end_12
    echo sflcvns.c missing - aborting
    goto exit
:end_12
 
:- require            sflcvsb.c  sflcvsd.c  sflcvsn.c  sflcvst.c
if exist sflcvsb.c goto end_13
    echo sflcvsb.c missing - aborting
    goto exit
:end_13
if exist sflcvsd.c goto end_14
    echo sflcvsd.c missing - aborting
    goto exit
:end_14
if exist sflcvsn.c goto end_15
    echo sflcvsn.c missing - aborting
    goto exit
:end_15
if exist sflcvst.c goto end_16
    echo sflcvst.c missing - aborting
    goto exit
:end_16
 
:- require            sflcvtp.c  sflcvts.c  sflconv.c
if exist sflcvtp.c goto end_17
    echo sflcvtp.c missing - aborting
    goto exit
:end_17
if exist sflcvts.c goto end_18
    echo sflcvts.c missing - aborting
    goto exit
:end_18
if exist sflconv.c goto end_19
    echo sflconv.c missing - aborting
    goto exit
:end_19
 
:- require sflcryp.h  sflcryp.c
if exist sflcryp.h goto end_20
    echo sflcryp.h missing - aborting
    goto exit
:end_20
if exist sflcryp.c goto end_21
    echo sflcryp.c missing - aborting
    goto exit
:end_21
 
:- require sfldate.h  sfldate.c
if exist sfldate.h goto end_22
    echo sfldate.h missing - aborting
    goto exit
:end_22
if exist sfldate.c goto end_23
    echo sfldate.c missing - aborting
    goto exit
:end_23
 
:- require sfldir.h   sfldir.c
if exist sfldir.h goto end_24
    echo sfldir.h missing - aborting
    goto exit
:end_24
if exist sfldir.c goto end_25
    echo sfldir.c missing - aborting
    goto exit
:end_25
 
:- require sflenv.h   sflenv.c
if exist sflenv.h goto end_26
    echo sflenv.h missing - aborting
    goto exit
:end_26
if exist sflenv.c goto end_27
    echo sflenv.c missing - aborting
    goto exit
:end_27
 
:- require sflexdr.h  sflexdr.c
if exist sflexdr.h goto end_28
    echo sflexdr.h missing - aborting
    goto exit
:end_28
if exist sflexdr.c goto end_29
    echo sflexdr.c missing - aborting
    goto exit
:end_29
 
:- require sflfile.h  sflfile.c
if exist sflfile.h goto end_30
    echo sflfile.h missing - aborting
    goto exit
:end_30
if exist sflfile.c goto end_31
    echo sflfile.c missing - aborting
    goto exit
:end_31
 
:- require sflfind.h  sflfind.c
if exist sflfind.h goto end_32
    echo sflfind.h missing - aborting
    goto exit
:end_32
if exist sflfind.c goto end_33
    echo sflfind.c missing - aborting
    goto exit
:end_33
 
:- require sflini.h   sflini.c
if exist sflini.h goto end_34
    echo sflini.h missing - aborting
    goto exit
:end_34
if exist sflini.c goto end_35
    echo sflini.c missing - aborting
    goto exit
:end_35
 
:- require sflmath.h  sflmath.c
if exist sflmath.h goto end_36
    echo sflmath.h missing - aborting
    goto exit
:end_36
if exist sflmath.c goto end_37
    echo sflmath.c missing - aborting
    goto exit
:end_37
 
:- require sflmem.h   sflmem.c
if exist sflmem.h goto end_38
    echo sflmem.h missing - aborting
    goto exit
:end_38
if exist sflmem.c goto end_39
    echo sflmem.c missing - aborting
    goto exit
:end_39
 
:- require sflmesg.h  sflmesg.c
if exist sflmesg.h goto end_40
    echo sflmesg.h missing - aborting
    goto exit
:end_40
if exist sflmesg.c goto end_41
    echo sflmesg.c missing - aborting
    goto exit
:end_41
 
:- require sflmime.h  sflmime.c
if exist sflmime.h goto end_42
    echo sflmime.h missing - aborting
    goto exit
:end_42
if exist sflmime.c goto end_43
    echo sflmime.c missing - aborting
    goto exit
:end_43
 
:- require sflnode.h  sflnode.c
if exist sflnode.h goto end_44
    echo sflnode.h missing - aborting
    goto exit
:end_44
if exist sflnode.c goto end_45
    echo sflnode.c missing - aborting
    goto exit
:end_45
 
:- require sflproc.h  sflproc.c
if exist sflproc.h goto end_46
    echo sflproc.h missing - aborting
    goto exit
:end_46
if exist sflproc.c goto end_47
    echo sflproc.c missing - aborting
    goto exit
:end_47
 
:- require sflslot.h  sflslot.c
if exist sflslot.h goto end_48
    echo sflslot.h missing - aborting
    goto exit
:end_48
if exist sflslot.c goto end_49
    echo sflslot.c missing - aborting
    goto exit
:end_49
 
:- require sflsock.h  sflsock.c
if exist sflsock.h goto end_50
    echo sflsock.h missing - aborting
    goto exit
:end_50
if exist sflsock.c goto end_51
    echo sflsock.c missing - aborting
    goto exit
:end_51
 
:- require sflstr.h   sflstr.c
if exist sflstr.h goto end_52
    echo sflstr.h missing - aborting
    goto exit
:end_52
if exist sflstr.c goto end_53
    echo sflstr.c missing - aborting
    goto exit
:end_53
 
:- require sflsymb.h  sflsymb.c
if exist sflsymb.h goto end_54
    echo sflsymb.h missing - aborting
    goto exit
:end_54
if exist sflsymb.c goto end_55
    echo sflsymb.c missing - aborting
    goto exit
:end_55
 
:- require sfltok.h   sfltok.c
if exist sfltok.h goto end_56
    echo sfltok.h missing - aborting
    goto exit
:end_56
if exist sfltok.c goto end_57
    echo sfltok.c missing - aborting
    goto exit
:end_57
 
:- require sfltron.h  sfltron.c
if exist sfltron.h goto end_58
    echo sfltron.h missing - aborting
    goto exit
:end_58
if exist sfltron.c goto end_59
    echo sfltron.c missing - aborting
    goto exit
:end_59
 
:- require sfluid.h   sfluid.c
if exist sfluid.h goto end_60
    echo sfluid.h missing - aborting
    goto exit
:end_60
if exist sfluid.c goto end_61
    echo sfluid.c missing - aborting
    goto exit
:end_61
 
:- library libsfl
del libsfl.lib
%LIB% libsfl
 
:- compile sflbits
%CC% %CFLAGS% sflbits
if errorlevel 1 goto exit
%LIB% libsfl +sflbits
del sflbits.obj
 
:- compile sflcgi
%CC% %CFLAGS% sflcgi
if errorlevel 1 goto exit
%LIB% libsfl +sflcgi
del sflcgi.obj
 
:- compile sflcomp
%CC% %CFLAGS% sflcomp
if errorlevel 1 goto exit
%LIB% libsfl +sflcomp
del sflcomp.obj
 
:- compile sflcryp
%CC% %CFLAGS% sflcryp
if errorlevel 1 goto exit
%LIB% libsfl +sflcryp
del sflcryp.obj
 
:- compile sflcvbs sflcvdp sflcvds sflcvns
%CC% %CFLAGS% sflcvbs
if errorlevel 1 goto exit
%LIB% libsfl +sflcvbs
del sflcvbs.obj
%CC% %CFLAGS% sflcvdp
if errorlevel 1 goto exit
%LIB% libsfl +sflcvdp
del sflcvdp.obj
%CC% %CFLAGS% sflcvds
if errorlevel 1 goto exit
%LIB% libsfl +sflcvds
del sflcvds.obj
%CC% %CFLAGS% sflcvns
if errorlevel 1 goto exit
%LIB% libsfl +sflcvns
del sflcvns.obj
 
:- compile sflcvsb sflcvsd sflcvsn sflcvst
%CC% %CFLAGS% sflcvsb
if errorlevel 1 goto exit
%LIB% libsfl +sflcvsb
del sflcvsb.obj
%CC% %CFLAGS% sflcvsd
if errorlevel 1 goto exit
%LIB% libsfl +sflcvsd
del sflcvsd.obj
%CC% %CFLAGS% sflcvsn
if errorlevel 1 goto exit
%LIB% libsfl +sflcvsn
del sflcvsn.obj
%CC% %CFLAGS% sflcvst
if errorlevel 1 goto exit
%LIB% libsfl +sflcvst
del sflcvst.obj
 
:- compile sflcvtp sflcvts sflconv
%CC% %CFLAGS% sflcvtp
if errorlevel 1 goto exit
%LIB% libsfl +sflcvtp
del sflcvtp.obj
%CC% %CFLAGS% sflcvts
if errorlevel 1 goto exit
%LIB% libsfl +sflcvts
del sflcvts.obj
%CC% %CFLAGS% sflconv
if errorlevel 1 goto exit
%LIB% libsfl +sflconv
del sflconv.obj
 
:- compile sfldate
%CC% %CFLAGS% sfldate
if errorlevel 1 goto exit
%LIB% libsfl +sfldate
del sfldate.obj
 
:- compile sfldir
%CC% %CFLAGS% sfldir
if errorlevel 1 goto exit
%LIB% libsfl +sfldir
del sfldir.obj
 
:- compile sflenv
%CC% %CFLAGS% sflenv
if errorlevel 1 goto exit
%LIB% libsfl +sflenv
del sflenv.obj
 
:- compile sflexdr
%CC% %CFLAGS% sflexdr
if errorlevel 1 goto exit
%LIB% libsfl +sflexdr
del sflexdr.obj
 
:- compile sflfile
%CC% %CFLAGS% sflfile
if errorlevel 1 goto exit
%LIB% libsfl +sflfile
del sflfile.obj
 
:- compile sflfind
%CC% %CFLAGS% sflfind
if errorlevel 1 goto exit
%LIB% libsfl +sflfind
del sflfind.obj
 
:- compile sflini
%CC% %CFLAGS% sflini
if errorlevel 1 goto exit
%LIB% libsfl +sflini
del sflini.obj
 
:- compile sflmath
%CC% %CFLAGS% sflmath
if errorlevel 1 goto exit
%LIB% libsfl +sflmath
del sflmath.obj
 
:- compile sflmem
%CC% %CFLAGS% sflmem
if errorlevel 1 goto exit
%LIB% libsfl +sflmem
del sflmem.obj
 
:- compile sflmesg
%CC% %CFLAGS% sflmesg
if errorlevel 1 goto exit
%LIB% libsfl +sflmesg
del sflmesg.obj
 
:- compile sflmime
%CC% %CFLAGS% sflmime
if errorlevel 1 goto exit
%LIB% libsfl +sflmime
del sflmime.obj
 
:- compile sflnode
%CC% %CFLAGS% sflnode
if errorlevel 1 goto exit
%LIB% libsfl +sflnode
del sflnode.obj
 
:- compile sflproc
%CC% %CFLAGS% sflproc
if errorlevel 1 goto exit
%LIB% libsfl +sflproc
del sflproc.obj
 
:- compile sflslot
%CC% %CFLAGS% sflslot
if errorlevel 1 goto exit
%LIB% libsfl +sflslot
del sflslot.obj
 
:- compile sflsock
%CC% %CFLAGS% sflsock
if errorlevel 1 goto exit
%LIB% libsfl +sflsock
del sflsock.obj
 
:- compile sflstr
%CC% %CFLAGS% sflstr
if errorlevel 1 goto exit
%LIB% libsfl +sflstr
del sflstr.obj
 
:- compile sflsymb
%CC% %CFLAGS% sflsymb
if errorlevel 1 goto exit
%LIB% libsfl +sflsymb
del sflsymb.obj
 
:- compile sfltok
%CC% %CFLAGS% sfltok
if errorlevel 1 goto exit
%LIB% libsfl +sfltok
del sfltok.obj
 
:- compile sfltron
%CC% %CFLAGS% sfltron
if errorlevel 1 goto exit
%LIB% libsfl +sfltron
del sfltron.obj
 
:- compile sfluid
%CC% %CFLAGS% sfluid
if errorlevel 1 goto exit
%LIB% libsfl +sfluid
del sfluid.obj
 
:- call buildh
call buildh
@echo off
echo.
echo SFL built successfully.

:exit
:---- delete all variables that initialed at the begining
echo.
set CCNAME=
set CCDIR=
set INCDEF=
set LIBDIR=
set CC=
set CFLAGS=
set LIB=
